# Generated by Django 5.2.1 on 2025-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Налично'), ('ordered', 'Поръчано'), ('completed', 'Завършено')], default='available', max_length=20),
        ),
    ]
