# Generated by Django 5.2.1 on 2025-07-08 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0001_initial'),
        ('listings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage_off', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(max_length=10, unique=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customauth.businessuser')),
                ('listing', models.ManyToManyField(to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
