# Generated by Django 5.2.1 on 2025-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='connection',
        ),
        migrations.AddField(
            model_name='promocode',
            name='connection',
            field=models.ManyToManyField(to='customauth.businessuser'),
        ),
    ]
