# Generated by Django 5.2.1 on 2025-07-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
        ('listings', '0001_initial'),
        ('promocodes', '0002_remove_promocode_connection_promocode_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='listing',
        ),
        migrations.AddField(
            model_name='promocode',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customauth.businessuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='listing',
            field=models.ManyToManyField(to='listings.listing'),
        ),
    ]
