# Generated by Django 5.2.1 on 2025-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='business_type',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('other', 'Other')], max_length=10),
        ),
    ]
