# Generated by Django 5.2.1 on 2025-06-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessuser',
            options={'permissions': (('can_create_listing', 'Can Create Listing'), ('can_edit_listing', 'Can Edit Listing'), ('can_delete_listing', 'Can Delete Listing'), ('can_read_listing', 'Can Read Listing'))},
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'permissions': (('can_order_listing', 'Can Order Listing - deletes order from Client to Business Side'),)},
        ),
    ]
