# Generated by Django 5.2.1 on 2025-06-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basespasihranauser',
            options={'verbose_name': 'All User', 'verbose_name_plural': 'All users'},
        ),
    ]
