# Generated by Django 5.2.1 on 2025-08-01 14:48

import customauth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basespasihranauser',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[customauth.validators.BulgarianPhoneNumberValidator()]),
        ),
    ]
