# Generated by Django 5.2.1 on 2025-05-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basespasihranauser',
            managers=[
            ],
        ),
    ]
