# Generated by Django 5.2.1 on 2025-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pfps'),
        ),
    ]
