# Generated by Django 5.2.1 on 2025-07-21 13:27

import django.contrib.auth.mixins
import django.db.models.deletion
import django.views.generic.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_code', models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customauth.businessuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customauth.customeruser')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
